# Generated by Django 3.2 on 2022-03-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=250)),
                ('nacionalidad_cliente', models.CharField(max_length=250)),
                ('tipo_documento_cliente', models.CharField(max_length=250)),
                ('nro_documento_cliente', models.IntegerField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='contactos',
            fields=[
                ('id_contacto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(max_length=250)),
                ('nacionalidad_contacto', models.CharField(max_length=250)),
                ('tipo_documento_contacto', models.CharField(max_length=250)),
                ('nro_documento_contacto', models.IntegerField(verbose_name='')),
                ('email_contacto', models.EmailField(max_length=254)),
                ('texto_consulta_contacto', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='habitaciones',
            fields=[
                ('numero_habitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_habitacion', models.CharField(max_length=250)),
                ('camas', models.IntegerField()),
                ('servicios_extras', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente_reserva', models.CharField(max_length=250)),
                ('qde_adultos_reserva', models.IntegerField()),
                ('qde_menores_reserva', models.IntegerField()),
                ('entrada_reserva', models.DateField()),
                ('salida_reserva', models.DateField()),
                ('tipo_habitacion_reserva', models.CharField(max_length=250)),
                ('email_cliente_reserva', models.EmailField(max_length=254)),
            ],
        ),
    ]
